sudo: false
language: python
python:
  - "2.7"
  - "3.5"
cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TZ=UTC

install:
  - pip install coveralls
  - pip install wheel
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - flake8
  - py.test --cov=vumi_msisdn_normalize_middleware --cov-report=term

after_success:
  - coveralls
